### ISSUE TITLE
Can you release the adversarial example generation code or more adversarial examples with noise radius 2/255,4/255,8/255?

### ISSUE THREAD

**Issue by KululuMi** [liuyixin-louis/MetaCloak#1]
Thanks for your interesting work which inspired me a lot! Can you release the adversarial example generation code or more adversarial examples with noise radius 2/255,4/255,8/255?

**Comment by liuyixin-louis** [comment]
Hi! Thank you for your interest in this work. We plan to release the code soon since we are still cleaning them up. And yes, I can share the perturbed images these days. Stay tuned.

**Comment by liuyixin-louis** [comment]
Hi, thank for your patience. We just release our code, and you can train the perturbed images by yourself on different noise level. Let me know if you need any other information or help.
