### ISSUE TITLE
can't install xformers==0.0.17.dev461

### ISSUE THREAD

**Issue by ainu412** [liuyixin-louis/MetaCloak#2]
after I run the command 'pip install xformers==0.0.17.dev461', it shows the following error:

ERROR: Could not find a version that satisfies the requirement xformers==0.0.17.dev461 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.16rc424, 0.0.16rc425, 0.0.16, 0.0.17rc481, 0.0.17rc482, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21, 0.0.22, 0.0.22.post7, 0.0.23, 0.0.23.post1, 0.0.24, 0.0.25, 0.0.25.post1, 0.0.26.dev777, 0.0.26.dev778)
ERROR: No matching distribution found for xformers==0.0.17.dev461

**Comment by liuyixin-louis** [comment]
Hi, try this version instead: xformers==0.0.16

**Comment by ainu412** [comment]
Hi, after I run "pip install xformers==0.0.16" and then run "sh scripts/gen_and_eval.sh", it shows the following xformer installation error:

04/22/2024 11:20:59 - INFO - __main__ - Distributed environment: DistributedType.NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda
Mixed precision type: fp16

summary of the attacker:
radius: 11.0
steps: 6
step_size: 1.1
random_start: False
norm_type: l-infty
ascending: True
sample_num: 1
x_range: 0 ~ 255

stabilityai/stable-diffusion-2-1-base
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
{'conv_in_kernel', 'upcast_attention', 'mid_block_type', 'resnet_time_scale_shift', 'conv_out_kernel', 'timestep_post_act', 'time_cond_proj_dim', 'projection_class_embeddings_input_dim', 'class_embed_type', 'time_embedding_type'} was not found in config. Values will be initialized to default values.
{'variance_type', 'clip_sample_range'} was not found in config. Values will be initialized to default values.
{'scaling_factor'} was not found in config. Values will be initialized to default values.
You selected to used efficient xformers
Make sure to install the following packages before continue
pip install triton==2.0.0.dev20221031
pip install pip install xformers==0.0.17.dev461
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /mnt/c/Users/ziyi.guo/Documents/GitHub/MetaCloak/robust_facecloak/attacks/algs/metacloak.py:625  │
│ in <module>                                                                                      │
│                                                                                                  │
│   622 │   # wandb.init(project="metacloak", entity=args.wandb_entity_name)                       │
│   623 │   # wandb.config.update(args)                                                            │
│   624 │   # wandb.log({'status': 'gen'})                                                         │
│ ❱ 625 │   main(args)                                                                             │
│   626                                                                                            │
│                                                                                                  │
│ /mnt/c/Users/ziyi.guo/Documents/GitHub/MetaCloak/robust_facecloak/attacks/algs/metacloak.py:518  │
│ in main                                                                                          │
│                                                                                                  │
│   515 │   model_paths = list(args.pretrained_model_name_or_path.split(","))                      │
│   516 │   num_models = len(model_paths)                                                          │
│   517 │                                                                                          │
│ ❱ 518 │   MODEL_BANKS = [load_model(args, path) for path in model_paths]                         │
│   519 │   MODEL_STATEDICTS = [                                                                   │
│   520 │   │   {                                                                                  │
│   521 │   │   │   "text_encoder": MODEL_BANKS[i][0].state_dict(),                                │
│                                                                                                  │
│ /mnt/c/Users/ziyi.guo/Documents/GitHub/MetaCloak/robust_facecloak/attacks/algs/metacloak.py:518  │
│ in <listcomp>                                                                                    │
│                                                                                                  │
│   515 │   model_paths = list(args.pretrained_model_name_or_path.split(","))                      │
│   516 │   num_models = len(model_paths)                                                          │
│   517 │                                                                                          │
│ ❱ 518 │   MODEL_BANKS = [load_model(args, path) for path in model_paths]                         │
│   519 │   MODEL_STATEDICTS = [                                                                   │
│   520 │   │   {                                                                                  │
│   521 │   │   │   "text_encoder": MODEL_BANKS[i][0].state_dict(),                                │
│                                                                                                  │
│ /mnt/c/Users/ziyi.guo/Documents/GitHub/MetaCloak/robust_facecloak/attacks/algs/metacloak.py:206  │
│ in load_model                                                                                    │
│                                                                                                  │
│   203 │   │   print("pip install triton==2.0.0.dev20221031")                                     │
│   204 │   │   print("pip install pip install xformers==0.0.17.dev461")                           │
│   205 │   │                                                                                      │
│ ❱ 206 │   │   unet.enable_xformers_memory_efficient_attention()                                  │
│   207 │                                                                                          │
│   208 │   return text_encoder, unet, tokenizer, noise_scheduler, vae                             │
│   209                                                                                            │
│                                                                                                  │
│ /home/ziyi/anaconda3/lib/python3.11/site-packages/diffusers/models/modeling_utils.py:251 in      │
│ enable_xformers_memory_efficient_attention                                                       │
│                                                                                                  │
│   248 │   │   >>> model.enable_xformers_memory_efficient_attention(attention_op=MemoryEfficien   │
│   249 │   │   ```                                                                                │
│   250 │   │   """                                                                                │
│ ❱ 251 │   │   self.set_use_memory_efficient_attention_xformers(True, attention_op)               │
│   252 │                                                                                          │
│   253 │   def disable_xformers_memory_efficient_attention(self):                                 │
│   254 │   │   r"""                                                                               │
│                                                                                                  │
│ /home/ziyi/anaconda3/lib/python3.11/site-packages/diffusers/models/modeling_utils.py:219 in      │
│ set_use_memory_efficient_attention_xformers                                                      │
│                                                                                                  │
│   216 │   │                                                                                      │
│   217 │   │   for module in self.children():                                                     │
│   218 │   │   │   if isinstance(module, torch.nn.Module):                                        │
│ ❱ 219 │   │   │   │   fn_recursive_set_mem_eff(module)                                           │
│   220 │                                                                                          │
│   221 │   def enable_xformers_memory_efficient_attention(self, attention_op: Optional[Callable   │
│   222 │   │   r"""                                                                               │
│                                                                                                  │
│ /home/ziyi/anaconda3/lib/python3.11/site-packages/diffusers/models/modeling_utils.py:215 in      │
│ fn_recursive_set_mem_eff                                                                         │
│                                                                                                  │
│   212 │   │   │   │   module.set_use_memory_efficient_attention_xformers(valid, attention_op)    │
│   213 │   │   │                                                                                  │
│   214 │   │   │   for child in module.children():                                                │
│ ❱ 215 │   │   │   │   fn_recursive_set_mem_eff(child)                                            │
│   216 │   │                                                                                      │
│   217 │   │   for module in self.children():                                                     │
│   218 │   │   │   if isinstance(module, torch.nn.Module):                                        │
│                                                                                                  │
│ /home/ziyi/anaconda3/lib/python3.11/site-packages/diffusers/models/modeling_utils.py:215 in      │
│ fn_recursive_set_mem_eff                                                                         │
│                                                                                                  │
│   212 │   │   │   │   module.set_use_memory_efficient_attention_xformers(valid, attention_op)    │
│   213 │   │   │                                                                                  │
│   214 │   │   │   for child in module.children():                                                │
│ ❱ 215 │   │   │   │   fn_recursive_set_mem_eff(child)                                            │
│   216 │   │                                                                                      │
│   217 │   │   for module in self.children():                                                     │
│   218 │   │   │   if isinstance(module, torch.nn.Module):                                        │
│                                                                                                  │
│ /home/ziyi/anaconda3/lib/python3.11/site-packages/diffusers/models/modeling_utils.py:215 in      │
│ fn_recursive_set_mem_eff                                                                         │
│                                                                                                  │
│   212 │   │   │   │   module.set_use_memory_efficient_attention_xformers(valid, attention_op)    │
│   213 │   │   │                                                                                  │
│   214 │   │   │   for child in module.children():                                                │
│ ❱ 215 │   │   │   │   fn_recursive_set_mem_eff(child)                                            │
│   216 │   │                                                                                      │
│   217 │   │   for module in self.children():                                                     │
│   218 │   │   │   if isinstance(module, torch.nn.Module):                                        │
│                                                                                                  │
│ /home/ziyi/anaconda3/lib/python3.11/site-packages/diffusers/models/modeling_utils.py:212 in      │
│ fn_recursive_set_mem_eff                                                                         │
│                                                                                                  │
│   209 │   │   # gets the message                                                                 │
│   210 │   │   def fn_recursive_set_mem_eff(module: torch.nn.Module):                             │
│   211 │   │   │   if hasattr(module, "set_use_memory_efficient_attention_xformers"):             │
│ ❱ 212 │   │   │   │   module.set_use_memory_efficient_attention_xformers(valid, attention_op)    │
│   213 │   │   │                                                                                  │
│   214 │   │   │   for child in module.children():                                                │
│   215 │   │   │   │   fn_recursive_set_mem_eff(child)                                            │
│                                                                                                  │
│ /home/ziyi/anaconda3/lib/python3.11/site-packages/diffusers/models/modeling_utils.py:219 in      │
│ set_use_memory_efficient_attention_xformers                                                      │
│                                                                                                  │
│   216 │   │                                                                                      │
│   217 │   │   for module in self.children():                                                     │
│   218 │   │   │   if isinstance(module, torch.nn.Module):                                        │
│ ❱ 219 │   │   │   │   fn_recursive_set_mem_eff(module)                                           │
│   220 │                                                                                          │
│   221 │   def enable_xformers_memory_efficient_attention(self, attention_op: Optional[Callable   │
│   222 │   │   r"""                                                                               │
│                                                                                                  │
│ /home/ziyi/anaconda3/lib/python3.11/site-packages/diffusers/models/modeling_utils.py:215 in      │
│ fn_recursive_set_mem_eff                                                                         │
│                                                                                                  │
│   212 │   │   │   │   module.set_use_memory_efficient_attention_xformers(valid, attention_op)    │
│   213 │   │   │                                                                                  │
│   214 │   │   │   for child in module.children():                                                │
│ ❱ 215 │   │   │   │   fn_recursive_set_mem_eff(child)                                            │
│   216 │   │                                                                                      │
│   217 │   │   for module in self.children():                                                     │
│   218 │   │   │   if isinstance(module, torch.nn.Module):                                        │
│                                                                                                  │
│ /home/ziyi/anaconda3/lib/python3.11/site-packages/diffusers/models/modeling_utils.py:215 in      │
│ fn_recursive_set_mem_eff                                                                         │
│                                                                                                  │
│   212 │   │   │   │   module.set_use_memory_efficient_attention_xformers(valid, attention_op)    │
│   213 │   │   │                                                                                  │
│   214 │   │   │   for child in module.children():                                                │
│ ❱ 215 │   │   │   │   fn_recursive_set_mem_eff(child)                                            │
│   216 │   │                                                                                      │
│   217 │   │   for module in self.children():                                                     │
│   218 │   │   │   if isinstance(module, torch.nn.Module):                                        │
│                                                                                                  │
│ /home/ziyi/anaconda3/lib/python3.11/site-packages/diffusers/models/modeling_utils.py:212 in      │
│ fn_recursive_set_mem_eff                                                                         │
│                                                                                                  │
│   209 │   │   # gets the message                                                                 │
│   210 │   │   def fn_recursive_set_mem_eff(module: torch.nn.Module):                             │
│   211 │   │   │   if hasattr(module, "set_use_memory_efficient_attention_xformers"):             │
│ ❱ 212 │   │   │   │   module.set_use_memory_efficient_attention_xformers(valid, attention_op)    │
│   213 │   │   │                                                                                  │
│   214 │   │   │   for child in module.children():                                                │
│   215 │   │   │   │   fn_recursive_set_mem_eff(child)                                            │
│                                                                                                  │
│ /home/ziyi/anaconda3/lib/python3.11/site-packages/diffusers/models/cross_attention.py:125 in     │
│ set_use_memory_efficient_attention_xformers                                                      │
│                                                                                                  │
│   122 │   │   │   │   │   " `self.added_kv_proj_dim` is defined."                                │
│   123 │   │   │   │   )                                                                          │
│   124 │   │   │   elif not is_xformers_available():                                              │
│ ❱ 125 │   │   │   │   raise ModuleNotFoundError(                                                 │
│   126 │   │   │   │   │   (                                                                      │
│   127 │   │   │   │   │   │   "Refer to https://github.com/facebookresearch/xformers for more    │
│   128 │   │   │   │   │   │   " xformers"                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: Refer to https://github.com/facebookresearch/xformers for more information on how to install
xformers
(metacloak) /mnt/c/Documents/GitHub/MetaCloak$ python
Python 3.9.18 (main, Sep 11 2023, 13:41:44)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xformers
>>> from diffusers.utils.import_utils import is_xformers_available
>>> is_xformers_available()
True
