### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets'

### ISSUE THREAD

**Issue by Au-LiuJY** [liuyixin-louis/MetaCloak#5]
I am more than delighted to see your great work to open source!
So,I want to run your demo to see the effect of this excellent work.
But,when I use "bash ./scripts/gen_and_eval.sh",the error occurs:
MetaCloak/robust_facecloak/attacks/algs/metacloak.py", line 20, in <module>
    import datasets
ModuleNotFoundError: No module named 'datasets'
But actually I have set all the required packages in my envs.
Like$ pip list
Package            Version
------------------ -----------
aiohappyeyeballs   2.4.3
aiohttp            3.10.10
aiosignal          1.3.1
async-timeout      4.0.3
attrs              24.2.0
bitsandbytes       0.44.2.dev0
Brotli             1.0.9
certifi            2024.8.30
charset-normalizer 3.3.2
clip               1.0
datasets           2.10.1
……
I  think the errors lies on the setting of the "PYTHONPATH",or "ADB_PROJECT_ROOT":
 echo $ADB_PROJECT_ROOT
/py_code/MetaCloak/
echo $PYTHONPATH
$:/py_code/MetaCloak/
Later,I change the PYTHONPATH to export PYTHONPATH="${PYTHONPATH:+$PYTHONPATH:}$ADB_PROJECT_ROOT"
And : echo $PYTHONPATH
/py_code/MetaCloak/

I want to know how to solve this problem.Thank you in advance!

**Comment by liuyixin-louis** [comment]
Hi please install datasets==2.10.1 following the requirement.txt
